import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/header"; // Import Header component
import Footer from "@/components/footer"; // Import Footer component

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* Global Header */}
        <Header />

        {/* Main Content */}
        <main className="container mx-auto px-4 py-8">{children}</main>

        {/* Global Footer */}
        <Footer />
      </body>
    </html>
  );
}
